spring.application.name=banking-transfer-api

# Server
server.port=8080

# H2 Database
spring.datasource.url=jdbc:h2:mem:bankingapidb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enables=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-uto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JWT Setting
app.jwt.secret=t4L0iIi0duGSVqUAzQ4854SQnJjKtEmsDhFfZJyZOW7v36YtNgtfLBcCBiF3yKujXd+CGhbiTMLMdj68vrY+sg==
app.jwt.expiration-ms=3600000

spring.jackson.deserialization.use-big-decimal-for-floats=true

# Logging
logging.level.org.springframework.security=DEBUG