spring.application.name=todo-api

# Server
server.port=8080

#H2 Database
spring.datasource.url=jdbc:h2:mem:tododb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JWT setting
app.jwt.secret=FrhFJkRXVQgBA1Ogsft+9NNNmvdzldEEFNzB6g/8dyudMyWpApH3+i7T653qQrmBsPXqYy5ZvD8St3V4+I8tmA==
app.jwt.expiration-ms=3600000

# Logging
logging.level.org.springframework.security=DEBUG